
member_details = {
                    "munna": {
                        "Name": "Arifur Rahman Munna",
                        "Designation": "Technology Manager",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "arif@hedigital.tech",
                        "Contact Number": "+8801571322757",
                        "Joining Date": "Aug-21",
                        "Date of Birth": "25-Dec",
                        "Blood Group": "O+",
                        "Linkedin": "https://www.linkedin.com/in/munnasorder/"
                    },
                    "rakib": {
                        "Name": "Md.Rakibul Hasan Naym",
                        "Designation": "Junior AI Engineer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "naym.mj@gmail.com",
                        "Contact Number": "+8801638830165",
                        "Joining Date": "Mar-23",
                        "Date of Birth": "5-Jun",
                        "Blood Group": "A+",
                        "Linkedin": "https://www.linkedin.com/in/md-rakibul-hasan-naym-625263229/"
                    },
                    "sakib": {
                        "Name": "Mahbubul Hasan Sakib",
                        "Designation": "Jr. Software Engineer(Node js)",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "mahbubulhasan179@gmail.com",
                        "Contact Number": "+8801812346095",
                        "Joining Date": "May-23",
                        "Date of Birth": "4-Aug",
                        "Blood Group": "O+",
                        "Linkedin": "https://www.linkedin.com/in/mhsakib29/"
                    },
                    "shahadat": {
                        "Name": "Md. Shahadot Hossain",
                        "Designation": "Jr. React Native Developer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "shahadotrahat786@gmail.com",
                        "Contact Number": "+8801775020582",
                        "Joining Date": "Jun-23",
                        "Date of Birth": "6-Feb",
                        "Blood Group": "B+",
                        "Linkedin": "https://www.linkedin.com/in/shahadot786/"
                    },
                    "minhaz": {
                        "Name": "S.M. Minhazul Abedin Shouhug",
                        "Designation": "Jr. React Native Developer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "minhazulabedin44@gmail.com",
                        "Contact Number": "+880182411744",
                        "Joining Date": "Jun-23",
                        "Date of Birth": "1-Jan",
                        "Blood Group": "B+",
                        "Linkedin": "https://www.linkedin.com/in/minhaz19/"
                    },
                    "himel": {
                        "Name": "Mehedi Mohammad Himel",
                        "Designation": "Junior AI Engineer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "himel@hedigital.tech",
                        "Contact Number": "+8801841021211",
                        "Joining Date": "Jun-23",
                        "Date of Birth": "20-Mar",
                        "Blood Group": "B+",
                        "Linkedin": "https://www.linkedin.com/in/mm-himel/"
                    },
                    "ferdous": {
                        "Name": "Mirza Ferdous Ohid",
                        "Designation": "Managing Director & CEO",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "ferdous@hedigital.tech",
                        "Contact Number": "+8801711081888",
                        # "Joining Date": "****",
                        "Date of Birth": "21-July",
                        "Blood Group": "O+",
                        "Linkedin": "https://www.linkedin.com/in/mirza-ferdous-ohid-70b16236/"
                    },
                    "aiyub": {
                        "Name": "Md. Aiyubali",
                        "Designation": "Jr. AI Engineer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "aiyub@hedigital.tech",
                        "Contact Number": "01650027810",
                        "Joining Date": "2-Dec-23",
                        "Date of Birth": "4-Jan-1999",
                        "Blood Group": "O+",
                        "Linkedin": "https://www.linkedin.com/in/md-aiyub-ali-b60173196/"
                    },
                    "shanin": {
                        "Name": "Md Shakhawat Hossain",
                        "Designation": "Jr. AI Engineer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "shanin@hedigital.tech",
                        "Contact Number": "01778198423",
                        "Joining Date": "15-Jan-2023",
                        "Date of Birth": "15-Jun-2001",
                        "Blood Group": "AB+",
                        "Linkedin": "https://www.linkedin.com/in/shanin-hossain/"
                    },
                    "walid": {
                        "Name": "Walid Al Hasan",
                        "Designation": "Intern",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "walid@hedigital.tech",
                        "Contact Number": "01792103884",
                        "Joining Date": "3-Feb-2024",
                        "Date of Birth": "25-May-2000",
                        "Blood Group": "A+",
                        "Linkedin": "https://www.linkedin.com/in/munsiwalidalhassannizhu"
                    },
                    "jony": {
                        "Name": "Md Razikul Islam Jony",
                        "Designation": "Jr. Frontend Developer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "razikuljoni@gmail.com",
                        "Contact Number": "01623208660",
                        "Joining Date": "11-Feb-2024",
                        "Date of Birth": "24-Oct-2001",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "waliullah": {
                        "Name": "Md Ollullah Sardar",
                        "Designation": "Jr. Backend Developer",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "oliullah@hedigital.tech",
                        "Contact Number": "01643616707",
                        "Joining Date": "2-Mar-2024",
                        "Date of Birth": "20-Jun-1998",
                        "Blood Group": "O+",
                        "Linkedin": ""
                    },
                    "sajal": {
                        "Name": "Mohammad Assaduzzaman",
                        "Designation": "Manager",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "sajal@hedigital.tech",
                        "Contact Number": "01321119233",
                        "Joining Date": "17-Jan-2020",
                        "Date of Birth": "24-Feb-1993",
                        "Blood Group": "O+",
                        "Linkedin": "https://www.linkedin.com/in/mohammad-assaduzzaman-855924116/"
                    },
                    "deba": {
                        "Name": "Deba Prasad Mistry",
                        "Designation": "",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "deba.hedigital@gmail.com",
                        "Contact Number": "01795807053",
                        "Joining Date": "10-Jan-2020",
                        "Date of Birth": "29-Dec-1995",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "nayem": {
                        "Name": "Saidul Alam Nayem",
                        "Designation": "Asst. Manager",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "nayem@hedigital.tech",
                        "Contact Number": "01321119224",
                        "Joining Date": "8-Jul-2020",
                        "Date of Birth": "29-Jan-1995",
                        "Blood Group": "AB+",
                        "Linkedin": "https://www.linkedin.com/in/saidul-alam-nayem/"
                    },
                    "rasel": {
                        "Name": "Rasedul Islam Rasel",
                        "Designation": "Senior Executive",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "rasel@hedigital.tech",
                        "Contact Number": "rasel@hedigital.tech",
                        "Joining Date": "10-Jan-2021",
                        "Date of Birth": "9-Jan-1994",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "sagor": {
                        "Name": "Md Mizanur Rahman Sagor",
                        "Designation": "Executive",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "Sagor@hedigital.tech",
                        "Contact Number": "01892479942",
                        "Joining Date": "2-Dec-2023",
                        "Date of Birth": "24-Apr-1997",
                        "Blood Group": "O+",
                        "Linkedin": ""
                    },
                    "tapan": {
                        "Name": "Tapan Sutradhar",
                        "Designation": "",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "tapan@hedigital.tech",
                        "Contact Number": "01721 294453",
                        "Joining Date": "23-Jul-2020",
                        "Date of Birth": "22-Dec-1996",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "imran": {
                        "Name": "Md Imran Hossain",
                        "Designation": "Junior Executive",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "Imran@hedigital.tech",
                        "Contact Number": "01329709023",
                        "Joining Date": "2-Mar-2024",
                        "Date of Birth": "29-Jul-1997",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "sabuj": {
                        "Name": "Fakir Rabiul Islam",
                        "Designation": "Executive ",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "rabuil.bght@gmail.com",
                        "Contact Number": "01722555199",
                        "Joining Date": "16-Nov-2023",
                        "Date of Birth": "6-Jun-1989",
                        "Blood Group": "A+",
                        "Linkedin": ""
                    },
                    "rahmat": {
                        "Name": "Md. Rahmat Ali",
                        "Designation": "Executive ",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "rahmat@hedigital.tech",
                        "Contact Number": "01321119231",
                        "Joining Date": "12-Jan-2021",
                        "Date of Birth": "12-Oct-1999",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "aymun": {
                        "Name": "Aymun Khan",
                        "Designation": "Executive ",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "ayman@hedigital.tech",
                        "Contact Number": "01329709025",
                        "Joining Date": "2-Jul-2023",
                        "Date of Birth": "31-May-1997",
                        "Blood Group": "O+",
                        "Linkedin": ""
                    },
                    "nadim": {
                        "Name": "Nadim Ahmmed",
                        "Designation": "Executive ",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "nadim@hedigital.tech",
                        "Contact Number": "01792303497",
                        "Joining Date": "10-Jan-2020",
                        "Date of Birth": "20-Sep-1995",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "tahmid": {
                        "Name": "Md Tahmidur Rahman",
                        "Designation": "Executive ",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "tahmid@hedigital.tech",
                        "Contact Number": "01750796337",
                        "Joining Date": "12-Jan-2021",
                        "Date of Birth": "24-Sep-1997",
                        "Blood Group": "B+",
                        "Linkedin": ""
                    },
                    "adnan": {
                        "Name": "M. A. Adnan",
                        "Designation": "Junior Executive",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "adnan@hedigital.tech",
                        "Contact Number": "01959225011",
                        "Joining Date": "15-Feb-2024",
                        "Date of Birth": "01 June 1995",
                        "Blood Group": "A+",
                        "Linkedin": ""
                    },
                    "saidul": {
                        "Name": "Saidul Alam Sarker",
                        "Designation": "",
                        "Organization": "HawkEyes Digital Monitoring Limited",
                        "E-mail": "",
                        "Contact Number": "",
                        "Joining Date": "",
                        "Date of Birth": "",
                        "Blood Group": "",
                        "Linkedin": ""
                    }
                }